import Core from "../../../core";
export default Core.Object({
  FirstParty: Core.String(),
  SecondParty: Core.String(),
  ContractDate: Core.String(),
  Property: Core.String(),
  ContractType: Core.String(),
  RentCurrency:Core.String(),
  IsFurnished: Core.Boolean(),
  ContractStarts: Core.String(),
  HandoverDate: Core.String(),
  PaidAmt: Core.Number(),
  ContractEnds: Core.String(),
  RequestedAmt: Core.Number(),
  PaidCurrency: Core.String(),
  RentFor: Core.String(),
  AdvanceAmt: Core.Number(),
  Lawyer: Core.String(),
  AdvanceCurrency: Core.String(),
  InsuranceAmt: Core.Number(),
  InsuranceCurrency: Core.String(),
  Remarks: Core.String(),
});
